baseURL = 'https://grandprixrealty.agency'
languageCode = 'en-us'
title = 'Grand Prix Realty - Las Vegas Real Estate & Property Management'
theme = 'grandprix'

[params]
  description = "Professional real estate services in Las Vegas - Home buying, selling, property management, and mortgage assistance"
  author = "Grand Prix Realty"
  location = "Las Vegas, Nevada"
  phone = ""
  email = ""

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Home Buyers"
    url = "/homebuyer/"
    weight = 2
  [[menu.main]]
    name = "Home Sellers"
    url = "/homeseller/"
    weight = 3
  [[menu.main]]
    name = "Property Management"
    url = "/propertymanagement/"
    weight = 4
  [[menu.main]]
    name = "Careers"
    url = "/careers/"
    weight = 5
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 6
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 7

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[build]
  writeStats = true

[params.seo]
  twitter_card = "summary_large_image"
  twitter_site = "@grandprixrealty"