baseURL = 'https://grandprixrealty.agency'
languageCode = 'en-us'
title = 'Grand Prix Realty - Las Vegas Real Estate & Property Management'
theme = 'grandprix'

# Permalinks for silo sections - keep URLs clean without /blog/
[permalinks]
  homebuyer = '/homebuyer/:slug/'
  homeseller = '/homeseller/:slug/'
  propertymanagement = '/propertymanagement/:slug/'
  realtors = '/realtors/:slug/'
  lasvegas = '/lasvegas/:slug/'

[params]
  description = "Professional real estate services in Las Vegas - Home buying, selling, property management, and mortgage assistance"
  author = "Grand Prix Realty"
  location = "Las Vegas, Nevada"
  phone = ""
  email = ""

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Home Buyers"
    url = "/homebuyer/"
    weight = 2
  [[menu.main]]
    name = "Home Sellers"
    url = "/homeseller/"
    weight = 3
  [[menu.main]]
    name = "Property Management"
    url = "/propertymanagement/"
    weight = 4
  [[menu.main]]
    name = "Careers"
    url = "/realtors/"
    weight = 5
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 6

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[build]
  writeStats = true

[params.seo]
  twitter_card = "summary_large_image"
  twitter_site = "@grandprixrealty"